#!/bin/bash

REPO="$HOME/.config/.repo"
CONFIG="$HOME/.config"
CONFIG_MAC="$HOME/Library/Application Support"

case "$1" in
    alacritty)
        source "$REPO/alacritty/setup"
        ;;
    aria2 | aria2c)
        source "$REPO/aria2/setup"
        ;;
    code | vscode)
        source "$REPO/Code/setup"
        ;;
    lazygit)
        source "$REPO/lazygit/setup"
        ;;
    pirate-get | pirateget)
        source "$REPO/pirate-get/setup"
        ;;
    ptpython)
        source "$REPO/ptpython/setup"
        ;;
    ripgrep | rg)
        source "$REPO/ripgrep/setup"
        ;;
    *)
        echo 'Make sure you enter the correct name to install'
        exit 1
        ;;

esac

for i in "${!dst[@]}"; do
    # make parent directories
    mkdir -p "$(dirname "${dst[i]}")"
    # create symlink
    ln -sf "${src[i]}" "${dst[i]}"
    # verify if link exists and is valid
    if [ -L ${my_link} ] && [ -e ${my_link} ]; then
        ls -l "${dst[i]}"
    fi
done
